CREATE SCHEMA MYSQL_TRAINING;

USE MYSQL_TRAINING;

DROP table EMPLOYEE;

CREATE TABLE EMPLOYEE (
    ID INT AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    AGE INT NOT NULL,
    GENDER CHAR(1),
    SALARY DOUBLE,
    DESIGNATION VARCHAR(50),
    DEPARTMENT VARCHAR(50),
    COUNTRY_ID INT,
    PRIMARY KEY (ID)
);

CREATE TABLE COUNTRY (
    ID INT AUTO_INCREMENT,
    CODE VARCHAR(3) NOT NULL,
    NAME VARCHAR(30) NOT NULL,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);

SELECT * FROM mysql_training.employee;

commit;